---
kind: pipeline
name: default

steps:
  - name: build
    image: golang:1.16-alpine
    commands:
      - GOOS=linux CGO_ENABLED=0 go build -ldflags="-s -w" -o serverchan serverchan.go

  - name: build-image
    image: plugins/docker
    settings:
      username: yakumioto
      password:
        from_secret: docker_password
      repo: yakumioto/drone-serverchan
      auto_tag: true

  - name: sendmsg
    image: yakumioto/drone-serverchan
    settings:
      key:
        from_secret: serverchan_key
      text: succeeded
      desp: docker build yakumioto/serverchan